### ISSUE TITLE
The answers of exercises are not themed

### ISSUE THREAD

**Issue by leo-gerv** [Vinetos/Xsinoi#2]
**Describe the bug**
Exercise's answers aren't visible. Background color is white.

**To Reproduce**
1. Go to any course and go into an exercise section
2. Validate the answer
3. Click on 'view solution'
4. See the problem

**Expected behavior**
Should be in dark

**Screenshots**
![Invisible answer](https://image.prntscr.com/image/GJJuawkVTpuK7PqAS8NH2w.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version 77

**Comment by Vinetos** [comment]
_Updating issue according to the issue template_
